/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteRouteImport } from './routes/home/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HomeFacultyIndexRouteImport } from './routes/home/faculty/index'
import { Route as HomeAboutIndexRouteImport } from './routes/home/about/index'

const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeFacultyIndexRoute = HomeFacultyIndexRouteImport.update({
  id: '/faculty/',
  path: '/faculty/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeAboutIndexRoute = HomeAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => HomeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRouteRouteWithChildren
  '/home/': typeof HomeIndexRoute
  '/home/about/': typeof HomeAboutIndexRoute
  '/home/faculty/': typeof HomeFacultyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeIndexRoute
  '/home/about': typeof HomeAboutIndexRoute
  '/home/faculty': typeof HomeFacultyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRouteRouteWithChildren
  '/home/': typeof HomeIndexRoute
  '/home/about/': typeof HomeAboutIndexRoute
  '/home/faculty/': typeof HomeFacultyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/home' | '/home/' | '/home/about/' | '/home/faculty/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home' | '/home/about' | '/home/faculty'
  id: '__root__' | '/' | '/home' | '/home/' | '/home/about/' | '/home/faculty/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/faculty/': {
      id: '/home/faculty/'
      path: '/faculty'
      fullPath: '/home/faculty/'
      preLoaderRoute: typeof HomeFacultyIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/about/': {
      id: '/home/about/'
      path: '/about'
      fullPath: '/home/about/'
      preLoaderRoute: typeof HomeAboutIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
  }
}

interface HomeRouteRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
  HomeAboutIndexRoute: typeof HomeAboutIndexRoute
  HomeFacultyIndexRoute: typeof HomeFacultyIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
  HomeAboutIndexRoute: HomeAboutIndexRoute,
  HomeFacultyIndexRoute: HomeFacultyIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRouteRoute: HomeRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
