/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteRouteImport } from './routes/user/route'
import { Route as HomeRouteRouteImport } from './routes/home/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UserCoursesRouteImport } from './routes/user/courses'
import { Route as UserSupportIndexRouteImport } from './routes/user/support/index'
import { Route as UserSettingsIndexRouteImport } from './routes/user/settings/index'
import { Route as UserProgressIndexRouteImport } from './routes/user/progress/index'
import { Route as UserNotificationsIndexRouteImport } from './routes/user/notifications/index'
import { Route as UserHistoryIndexRouteImport } from './routes/user/history/index'
import { Route as HomeProgramsIndexRouteImport } from './routes/home/programs/index'
import { Route as HomeContactIndexRouteImport } from './routes/home/contact/index'
import { Route as HomeAccreditationsIndexRouteImport } from './routes/home/accreditations/index'
import { Route as HomeAboutIndexRouteImport } from './routes/home/about/index'
import { Route as HomeAuthSignupRouteImport } from './routes/home/auth/signup'
import { Route as HomeAuthLoginRouteImport } from './routes/home/auth/login'
import { Route as HomeProgramsIdIndexRouteImport } from './routes/home/programs/$id/index'

const UserRouteRoute = UserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRouteRoute,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UserCoursesRoute = UserCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserSupportIndexRoute = UserSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserSettingsIndexRoute = UserSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserProgressIndexRoute = UserProgressIndexRouteImport.update({
  id: '/progress/',
  path: '/progress/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserNotificationsIndexRoute = UserNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserHistoryIndexRoute = UserHistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => UserRouteRoute,
} as any)
const HomeProgramsIndexRoute = HomeProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeContactIndexRoute = HomeContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeAccreditationsIndexRoute = HomeAccreditationsIndexRouteImport.update({
  id: '/accreditations/',
  path: '/accreditations/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeAboutIndexRoute = HomeAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeAuthSignupRoute = HomeAuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeAuthLoginRoute = HomeAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeProgramsIdIndexRoute = HomeProgramsIdIndexRouteImport.update({
  id: '/programs/$id/',
  path: '/programs/$id/',
  getParentRoute: () => HomeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/user/courses': typeof UserCoursesRoute
  '/admin/': typeof AdminIndexRoute
  '/home/': typeof HomeIndexRoute
  '/user/': typeof UserIndexRoute
  '/home/auth/login': typeof HomeAuthLoginRoute
  '/home/auth/signup': typeof HomeAuthSignupRoute
  '/home/about/': typeof HomeAboutIndexRoute
  '/home/accreditations/': typeof HomeAccreditationsIndexRoute
  '/home/contact/': typeof HomeContactIndexRoute
  '/home/programs/': typeof HomeProgramsIndexRoute
  '/user/history/': typeof UserHistoryIndexRoute
  '/user/notifications/': typeof UserNotificationsIndexRoute
  '/user/progress/': typeof UserProgressIndexRoute
  '/user/settings/': typeof UserSettingsIndexRoute
  '/user/support/': typeof UserSupportIndexRoute
  '/home/programs/$id/': typeof HomeProgramsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/user/courses': typeof UserCoursesRoute
  '/admin': typeof AdminIndexRoute
  '/home': typeof HomeIndexRoute
  '/user': typeof UserIndexRoute
  '/home/auth/login': typeof HomeAuthLoginRoute
  '/home/auth/signup': typeof HomeAuthSignupRoute
  '/home/about': typeof HomeAboutIndexRoute
  '/home/accreditations': typeof HomeAccreditationsIndexRoute
  '/home/contact': typeof HomeContactIndexRoute
  '/home/programs': typeof HomeProgramsIndexRoute
  '/user/history': typeof UserHistoryIndexRoute
  '/user/notifications': typeof UserNotificationsIndexRoute
  '/user/progress': typeof UserProgressIndexRoute
  '/user/settings': typeof UserSettingsIndexRoute
  '/user/support': typeof UserSupportIndexRoute
  '/home/programs/$id': typeof HomeProgramsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/user/courses': typeof UserCoursesRoute
  '/admin/': typeof AdminIndexRoute
  '/home/': typeof HomeIndexRoute
  '/user/': typeof UserIndexRoute
  '/home/auth/login': typeof HomeAuthLoginRoute
  '/home/auth/signup': typeof HomeAuthSignupRoute
  '/home/about/': typeof HomeAboutIndexRoute
  '/home/accreditations/': typeof HomeAccreditationsIndexRoute
  '/home/contact/': typeof HomeContactIndexRoute
  '/home/programs/': typeof HomeProgramsIndexRoute
  '/user/history/': typeof UserHistoryIndexRoute
  '/user/notifications/': typeof UserNotificationsIndexRoute
  '/user/progress/': typeof UserProgressIndexRoute
  '/user/settings/': typeof UserSettingsIndexRoute
  '/user/support/': typeof UserSupportIndexRoute
  '/home/programs/$id/': typeof HomeProgramsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/home'
    | '/user'
    | '/user/courses'
    | '/admin/'
    | '/home/'
    | '/user/'
    | '/home/auth/login'
    | '/home/auth/signup'
    | '/home/about/'
    | '/home/accreditations/'
    | '/home/contact/'
    | '/home/programs/'
    | '/user/history/'
    | '/user/notifications/'
    | '/user/progress/'
    | '/user/settings/'
    | '/user/support/'
    | '/home/programs/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/user/courses'
    | '/admin'
    | '/home'
    | '/user'
    | '/home/auth/login'
    | '/home/auth/signup'
    | '/home/about'
    | '/home/accreditations'
    | '/home/contact'
    | '/home/programs'
    | '/user/history'
    | '/user/notifications'
    | '/user/progress'
    | '/user/settings'
    | '/user/support'
    | '/home/programs/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/home'
    | '/user'
    | '/user/courses'
    | '/admin/'
    | '/home/'
    | '/user/'
    | '/home/auth/login'
    | '/home/auth/signup'
    | '/home/about/'
    | '/home/accreditations/'
    | '/home/contact/'
    | '/home/programs/'
    | '/user/history/'
    | '/user/notifications/'
    | '/user/progress/'
    | '/user/settings/'
    | '/user/support/'
    | '/home/programs/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/user/courses': {
      id: '/user/courses'
      path: '/courses'
      fullPath: '/user/courses'
      preLoaderRoute: typeof UserCoursesRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/support/': {
      id: '/user/support/'
      path: '/support'
      fullPath: '/user/support/'
      preLoaderRoute: typeof UserSupportIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/settings/': {
      id: '/user/settings/'
      path: '/settings'
      fullPath: '/user/settings/'
      preLoaderRoute: typeof UserSettingsIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/progress/': {
      id: '/user/progress/'
      path: '/progress'
      fullPath: '/user/progress/'
      preLoaderRoute: typeof UserProgressIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/notifications/': {
      id: '/user/notifications/'
      path: '/notifications'
      fullPath: '/user/notifications/'
      preLoaderRoute: typeof UserNotificationsIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/history/': {
      id: '/user/history/'
      path: '/history'
      fullPath: '/user/history/'
      preLoaderRoute: typeof UserHistoryIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/home/programs/': {
      id: '/home/programs/'
      path: '/programs'
      fullPath: '/home/programs/'
      preLoaderRoute: typeof HomeProgramsIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/contact/': {
      id: '/home/contact/'
      path: '/contact'
      fullPath: '/home/contact/'
      preLoaderRoute: typeof HomeContactIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/accreditations/': {
      id: '/home/accreditations/'
      path: '/accreditations'
      fullPath: '/home/accreditations/'
      preLoaderRoute: typeof HomeAccreditationsIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/about/': {
      id: '/home/about/'
      path: '/about'
      fullPath: '/home/about/'
      preLoaderRoute: typeof HomeAboutIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/auth/signup': {
      id: '/home/auth/signup'
      path: '/auth/signup'
      fullPath: '/home/auth/signup'
      preLoaderRoute: typeof HomeAuthSignupRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/auth/login': {
      id: '/home/auth/login'
      path: '/auth/login'
      fullPath: '/home/auth/login'
      preLoaderRoute: typeof HomeAuthLoginRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/programs/$id/': {
      id: '/home/programs/$id/'
      path: '/programs/$id'
      fullPath: '/home/programs/$id/'
      preLoaderRoute: typeof HomeProgramsIdIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface HomeRouteRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
  HomeAuthLoginRoute: typeof HomeAuthLoginRoute
  HomeAuthSignupRoute: typeof HomeAuthSignupRoute
  HomeAboutIndexRoute: typeof HomeAboutIndexRoute
  HomeAccreditationsIndexRoute: typeof HomeAccreditationsIndexRoute
  HomeContactIndexRoute: typeof HomeContactIndexRoute
  HomeProgramsIndexRoute: typeof HomeProgramsIndexRoute
  HomeProgramsIdIndexRoute: typeof HomeProgramsIdIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
  HomeAuthLoginRoute: HomeAuthLoginRoute,
  HomeAuthSignupRoute: HomeAuthSignupRoute,
  HomeAboutIndexRoute: HomeAboutIndexRoute,
  HomeAccreditationsIndexRoute: HomeAccreditationsIndexRoute,
  HomeContactIndexRoute: HomeContactIndexRoute,
  HomeProgramsIndexRoute: HomeProgramsIndexRoute,
  HomeProgramsIdIndexRoute: HomeProgramsIdIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserCoursesRoute: typeof UserCoursesRoute
  UserIndexRoute: typeof UserIndexRoute
  UserHistoryIndexRoute: typeof UserHistoryIndexRoute
  UserNotificationsIndexRoute: typeof UserNotificationsIndexRoute
  UserProgressIndexRoute: typeof UserProgressIndexRoute
  UserSettingsIndexRoute: typeof UserSettingsIndexRoute
  UserSupportIndexRoute: typeof UserSupportIndexRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserCoursesRoute: UserCoursesRoute,
  UserIndexRoute: UserIndexRoute,
  UserHistoryIndexRoute: UserHistoryIndexRoute,
  UserNotificationsIndexRoute: UserNotificationsIndexRoute,
  UserProgressIndexRoute: UserProgressIndexRoute,
  UserSettingsIndexRoute: UserSettingsIndexRoute,
  UserSupportIndexRoute: UserSupportIndexRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
