/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteRouteImport } from './routes/about/route'
import { Route as AccreditationsRouteRouteImport } from './routes/accreditations/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as BlogRouteRouteImport } from './routes/blog/route'
import { Route as CoursesRouteRouteImport } from './routes/courses/route'
import { Route as HomeRouteRouteImport } from './routes/home/route'
import { Route as UserRouteRouteImport } from './routes/user/route'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AccreditationsIndexRouteImport } from './routes/accreditations/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as CertificateIdRouteImport } from './routes/certificate/$id'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as PaymentCallbackRouteImport } from './routes/payment/callback'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as BlogIdIndexRouteImport } from './routes/blog/$id/index'
import { Route as CoursesIdIndexRouteImport } from './routes/courses/$id/index'
import { Route as HomeAuthLoginRouteImport } from './routes/home/auth/login'
import { Route as HomeAuthSignupRouteImport } from './routes/home/auth/signup'
import { Route as HomeContactIndexRouteImport } from './routes/home/contact/index'
import { Route as HomeFaqIndexRouteImport } from './routes/home/faq/index'
import { Route as HomeTermsIndexRouteImport } from './routes/home/terms/index'
import { Route as UserCoursesIndexRouteImport } from './routes/user/courses/index'
import { Route as UserCoursesIdRouteRouteImport } from './routes/user/courses/$id/route'
import { Route as UserNotificationsIndexRouteImport } from './routes/user/notifications/index'
import { Route as UserProgressIndexRouteImport } from './routes/user/progress/index'
import { Route as UserPurchaseHistoryIndexRouteImport } from './routes/user/purchase-history/index'
import { Route as UserSettingsIndexRouteImport } from './routes/user/settings/index'
import { Route as UserSupportIndexRouteImport } from './routes/user/support/index'
import { Route as VerifyIdIndexRouteImport } from './routes/verify/$id.index'
import { Route as HomeAuthVerifyIndexRouteImport } from './routes/home/auth/verify/index'
import { Route as UserCoursesIdIndexRouteImport } from './routes/user/courses/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRouteRoute = AboutRouteRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccreditationsRouteRoute = AccreditationsRouteRouteImport.update({
  id: '/accreditations',
  path: '/accreditations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRouteRoute = BlogRouteRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRouteRoute = CoursesRouteRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRouteRoute,
} as any)
const AccreditationsIndexRoute = AccreditationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccreditationsRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRouteRoute,
} as any)
const CertificateIdRoute = CertificateIdRouteImport.update({
  id: '/certificate/$id',
  path: '/certificate/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRouteRoute,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment/callback',
  path: '/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRouteRoute,
} as any)
const BlogIdIndexRoute = BlogIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => BlogRouteRoute,
} as any)
const CoursesIdIndexRoute = CoursesIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => CoursesRouteRoute,
} as any)
const HomeAuthLoginRoute = HomeAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeAuthSignupRoute = HomeAuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeContactIndexRoute = HomeContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeFaqIndexRoute = HomeFaqIndexRouteImport.update({
  id: '/faq/',
  path: '/faq/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeTermsIndexRoute = HomeTermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const UserCoursesIndexRoute = UserCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserCoursesIdRouteRoute = UserCoursesIdRouteRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserNotificationsIndexRoute = UserNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserProgressIndexRoute = UserProgressIndexRouteImport.update({
  id: '/progress/',
  path: '/progress/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserPurchaseHistoryIndexRoute =
  UserPurchaseHistoryIndexRouteImport.update({
    id: '/purchase-history/',
    path: '/purchase-history/',
    getParentRoute: () => UserRouteRoute,
  } as any)
const UserSettingsIndexRoute = UserSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserSupportIndexRoute = UserSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => UserRouteRoute,
} as any)
const VerifyIdIndexRoute = VerifyIdIndexRouteImport.update({
  id: '/verify/$id/',
  path: '/verify/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeAuthVerifyIndexRoute = HomeAuthVerifyIndexRouteImport.update({
  id: '/auth/verify/',
  path: '/auth/verify/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const UserCoursesIdIndexRoute = UserCoursesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserCoursesIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRouteWithChildren
  '/accreditations': typeof AccreditationsRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/blog': typeof BlogRouteRouteWithChildren
  '/courses': typeof CoursesRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/certificate/$id': typeof CertificateIdRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/about/': typeof AboutIndexRoute
  '/accreditations/': typeof AccreditationsIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/home/': typeof HomeIndexRoute
  '/test/': typeof TestIndexRoute
  '/user/': typeof UserIndexRoute
  '/user/courses/$id': typeof UserCoursesIdRouteRouteWithChildren
  '/home/auth/login': typeof HomeAuthLoginRoute
  '/home/auth/signup': typeof HomeAuthSignupRoute
  '/blog/$id/': typeof BlogIdIndexRoute
  '/courses/$id/': typeof CoursesIdIndexRoute
  '/home/contact/': typeof HomeContactIndexRoute
  '/home/faq/': typeof HomeFaqIndexRoute
  '/home/terms/': typeof HomeTermsIndexRoute
  '/user/courses/': typeof UserCoursesIndexRoute
  '/user/notifications/': typeof UserNotificationsIndexRoute
  '/user/progress/': typeof UserProgressIndexRoute
  '/user/purchase-history/': typeof UserPurchaseHistoryIndexRoute
  '/user/settings/': typeof UserSettingsIndexRoute
  '/user/support/': typeof UserSupportIndexRoute
  '/verify/$id/': typeof VerifyIdIndexRoute
  '/home/auth/verify/': typeof HomeAuthVerifyIndexRoute
  '/user/courses/$id/': typeof UserCoursesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificate/$id': typeof CertificateIdRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/about': typeof AboutIndexRoute
  '/accreditations': typeof AccreditationsIndexRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/home': typeof HomeIndexRoute
  '/test': typeof TestIndexRoute
  '/user': typeof UserIndexRoute
  '/home/auth/login': typeof HomeAuthLoginRoute
  '/home/auth/signup': typeof HomeAuthSignupRoute
  '/blog/$id': typeof BlogIdIndexRoute
  '/courses/$id': typeof CoursesIdIndexRoute
  '/home/contact': typeof HomeContactIndexRoute
  '/home/faq': typeof HomeFaqIndexRoute
  '/home/terms': typeof HomeTermsIndexRoute
  '/user/courses': typeof UserCoursesIndexRoute
  '/user/notifications': typeof UserNotificationsIndexRoute
  '/user/progress': typeof UserProgressIndexRoute
  '/user/purchase-history': typeof UserPurchaseHistoryIndexRoute
  '/user/settings': typeof UserSettingsIndexRoute
  '/user/support': typeof UserSupportIndexRoute
  '/verify/$id': typeof VerifyIdIndexRoute
  '/home/auth/verify': typeof HomeAuthVerifyIndexRoute
  '/user/courses/$id': typeof UserCoursesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRouteWithChildren
  '/accreditations': typeof AccreditationsRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/blog': typeof BlogRouteRouteWithChildren
  '/courses': typeof CoursesRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/certificate/$id': typeof CertificateIdRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/about/': typeof AboutIndexRoute
  '/accreditations/': typeof AccreditationsIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/home/': typeof HomeIndexRoute
  '/test/': typeof TestIndexRoute
  '/user/': typeof UserIndexRoute
  '/user/courses/$id': typeof UserCoursesIdRouteRouteWithChildren
  '/home/auth/login': typeof HomeAuthLoginRoute
  '/home/auth/signup': typeof HomeAuthSignupRoute
  '/blog/$id/': typeof BlogIdIndexRoute
  '/courses/$id/': typeof CoursesIdIndexRoute
  '/home/contact/': typeof HomeContactIndexRoute
  '/home/faq/': typeof HomeFaqIndexRoute
  '/home/terms/': typeof HomeTermsIndexRoute
  '/user/courses/': typeof UserCoursesIndexRoute
  '/user/notifications/': typeof UserNotificationsIndexRoute
  '/user/progress/': typeof UserProgressIndexRoute
  '/user/purchase-history/': typeof UserPurchaseHistoryIndexRoute
  '/user/settings/': typeof UserSettingsIndexRoute
  '/user/support/': typeof UserSupportIndexRoute
  '/verify/$id/': typeof VerifyIdIndexRoute
  '/home/auth/verify/': typeof HomeAuthVerifyIndexRoute
  '/user/courses/$id/': typeof UserCoursesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accreditations'
    | '/admin'
    | '/blog'
    | '/courses'
    | '/home'
    | '/user'
    | '/certificate/$id'
    | '/payment/callback'
    | '/about/'
    | '/accreditations/'
    | '/admin/'
    | '/blog/'
    | '/courses/'
    | '/home/'
    | '/test/'
    | '/user/'
    | '/user/courses/$id'
    | '/home/auth/login'
    | '/home/auth/signup'
    | '/blog/$id/'
    | '/courses/$id/'
    | '/home/contact/'
    | '/home/faq/'
    | '/home/terms/'
    | '/user/courses/'
    | '/user/notifications/'
    | '/user/progress/'
    | '/user/purchase-history/'
    | '/user/settings/'
    | '/user/support/'
    | '/verify/$id/'
    | '/home/auth/verify/'
    | '/user/courses/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certificate/$id'
    | '/payment/callback'
    | '/about'
    | '/accreditations'
    | '/admin'
    | '/blog'
    | '/courses'
    | '/home'
    | '/test'
    | '/user'
    | '/home/auth/login'
    | '/home/auth/signup'
    | '/blog/$id'
    | '/courses/$id'
    | '/home/contact'
    | '/home/faq'
    | '/home/terms'
    | '/user/courses'
    | '/user/notifications'
    | '/user/progress'
    | '/user/purchase-history'
    | '/user/settings'
    | '/user/support'
    | '/verify/$id'
    | '/home/auth/verify'
    | '/user/courses/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accreditations'
    | '/admin'
    | '/blog'
    | '/courses'
    | '/home'
    | '/user'
    | '/certificate/$id'
    | '/payment/callback'
    | '/about/'
    | '/accreditations/'
    | '/admin/'
    | '/blog/'
    | '/courses/'
    | '/home/'
    | '/test/'
    | '/user/'
    | '/user/courses/$id'
    | '/home/auth/login'
    | '/home/auth/signup'
    | '/blog/$id/'
    | '/courses/$id/'
    | '/home/contact/'
    | '/home/faq/'
    | '/home/terms/'
    | '/user/courses/'
    | '/user/notifications/'
    | '/user/progress/'
    | '/user/purchase-history/'
    | '/user/settings/'
    | '/user/support/'
    | '/verify/$id/'
    | '/home/auth/verify/'
    | '/user/courses/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRouteRoute: typeof AboutRouteRouteWithChildren
  AccreditationsRouteRoute: typeof AccreditationsRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BlogRouteRoute: typeof BlogRouteRouteWithChildren
  CoursesRouteRoute: typeof CoursesRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
  CertificateIdRoute: typeof CertificateIdRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  TestIndexRoute: typeof TestIndexRoute
  VerifyIdIndexRoute: typeof VerifyIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accreditations': {
      id: '/accreditations'
      path: '/accreditations'
      fullPath: '/accreditations'
      preLoaderRoute: typeof AccreditationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRouteRoute
    }
    '/accreditations/': {
      id: '/accreditations/'
      path: '/'
      fullPath: '/accreditations/'
      preLoaderRoute: typeof AccreditationsIndexRouteImport
      parentRoute: typeof AccreditationsRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/certificate/$id': {
      id: '/certificate/$id'
      path: '/certificate/$id'
      fullPath: '/certificate/$id'
      preLoaderRoute: typeof CertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRouteRoute
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/payment/callback': {
      id: '/payment/callback'
      path: '/payment/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/blog/$id/': {
      id: '/blog/$id/'
      path: '/$id'
      fullPath: '/blog/$id/'
      preLoaderRoute: typeof BlogIdIndexRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/courses/$id/': {
      id: '/courses/$id/'
      path: '/$id'
      fullPath: '/courses/$id/'
      preLoaderRoute: typeof CoursesIdIndexRouteImport
      parentRoute: typeof CoursesRouteRoute
    }
    '/home/auth/login': {
      id: '/home/auth/login'
      path: '/auth/login'
      fullPath: '/home/auth/login'
      preLoaderRoute: typeof HomeAuthLoginRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/auth/signup': {
      id: '/home/auth/signup'
      path: '/auth/signup'
      fullPath: '/home/auth/signup'
      preLoaderRoute: typeof HomeAuthSignupRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/contact/': {
      id: '/home/contact/'
      path: '/contact'
      fullPath: '/home/contact/'
      preLoaderRoute: typeof HomeContactIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/faq/': {
      id: '/home/faq/'
      path: '/faq'
      fullPath: '/home/faq/'
      preLoaderRoute: typeof HomeFaqIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/terms/': {
      id: '/home/terms/'
      path: '/terms'
      fullPath: '/home/terms/'
      preLoaderRoute: typeof HomeTermsIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/user/courses/': {
      id: '/user/courses/'
      path: '/courses'
      fullPath: '/user/courses/'
      preLoaderRoute: typeof UserCoursesIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/courses/$id': {
      id: '/user/courses/$id'
      path: '/courses/$id'
      fullPath: '/user/courses/$id'
      preLoaderRoute: typeof UserCoursesIdRouteRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/notifications/': {
      id: '/user/notifications/'
      path: '/notifications'
      fullPath: '/user/notifications/'
      preLoaderRoute: typeof UserNotificationsIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/progress/': {
      id: '/user/progress/'
      path: '/progress'
      fullPath: '/user/progress/'
      preLoaderRoute: typeof UserProgressIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/purchase-history/': {
      id: '/user/purchase-history/'
      path: '/purchase-history'
      fullPath: '/user/purchase-history/'
      preLoaderRoute: typeof UserPurchaseHistoryIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/settings/': {
      id: '/user/settings/'
      path: '/settings'
      fullPath: '/user/settings/'
      preLoaderRoute: typeof UserSettingsIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/support/': {
      id: '/user/support/'
      path: '/support'
      fullPath: '/user/support/'
      preLoaderRoute: typeof UserSupportIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/verify/$id/': {
      id: '/verify/$id/'
      path: '/verify/$id'
      fullPath: '/verify/$id/'
      preLoaderRoute: typeof VerifyIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/auth/verify/': {
      id: '/home/auth/verify/'
      path: '/auth/verify'
      fullPath: '/home/auth/verify/'
      preLoaderRoute: typeof HomeAuthVerifyIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/user/courses/$id/': {
      id: '/user/courses/$id/'
      path: '/'
      fullPath: '/user/courses/$id/'
      preLoaderRoute: typeof UserCoursesIdIndexRouteImport
      parentRoute: typeof UserCoursesIdRouteRoute
    }
  }
}

interface AboutRouteRouteChildren {
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteRouteChildren: AboutRouteRouteChildren = {
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteRouteWithChildren = AboutRouteRoute._addFileChildren(
  AboutRouteRouteChildren,
)

interface AccreditationsRouteRouteChildren {
  AccreditationsIndexRoute: typeof AccreditationsIndexRoute
}

const AccreditationsRouteRouteChildren: AccreditationsRouteRouteChildren = {
  AccreditationsIndexRoute: AccreditationsIndexRoute,
}

const AccreditationsRouteRouteWithChildren =
  AccreditationsRouteRoute._addFileChildren(AccreditationsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface BlogRouteRouteChildren {
  BlogIndexRoute: typeof BlogIndexRoute
  BlogIdIndexRoute: typeof BlogIdIndexRoute
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  BlogIndexRoute: BlogIndexRoute,
  BlogIdIndexRoute: BlogIdIndexRoute,
}

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren,
)

interface CoursesRouteRouteChildren {
  CoursesIndexRoute: typeof CoursesIndexRoute
  CoursesIdIndexRoute: typeof CoursesIdIndexRoute
}

const CoursesRouteRouteChildren: CoursesRouteRouteChildren = {
  CoursesIndexRoute: CoursesIndexRoute,
  CoursesIdIndexRoute: CoursesIdIndexRoute,
}

const CoursesRouteRouteWithChildren = CoursesRouteRoute._addFileChildren(
  CoursesRouteRouteChildren,
)

interface HomeRouteRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
  HomeAuthLoginRoute: typeof HomeAuthLoginRoute
  HomeAuthSignupRoute: typeof HomeAuthSignupRoute
  HomeContactIndexRoute: typeof HomeContactIndexRoute
  HomeFaqIndexRoute: typeof HomeFaqIndexRoute
  HomeTermsIndexRoute: typeof HomeTermsIndexRoute
  HomeAuthVerifyIndexRoute: typeof HomeAuthVerifyIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
  HomeAuthLoginRoute: HomeAuthLoginRoute,
  HomeAuthSignupRoute: HomeAuthSignupRoute,
  HomeContactIndexRoute: HomeContactIndexRoute,
  HomeFaqIndexRoute: HomeFaqIndexRoute,
  HomeTermsIndexRoute: HomeTermsIndexRoute,
  HomeAuthVerifyIndexRoute: HomeAuthVerifyIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

interface UserCoursesIdRouteRouteChildren {
  UserCoursesIdIndexRoute: typeof UserCoursesIdIndexRoute
}

const UserCoursesIdRouteRouteChildren: UserCoursesIdRouteRouteChildren = {
  UserCoursesIdIndexRoute: UserCoursesIdIndexRoute,
}

const UserCoursesIdRouteRouteWithChildren =
  UserCoursesIdRouteRoute._addFileChildren(UserCoursesIdRouteRouteChildren)

interface UserRouteRouteChildren {
  UserIndexRoute: typeof UserIndexRoute
  UserCoursesIdRouteRoute: typeof UserCoursesIdRouteRouteWithChildren
  UserCoursesIndexRoute: typeof UserCoursesIndexRoute
  UserNotificationsIndexRoute: typeof UserNotificationsIndexRoute
  UserProgressIndexRoute: typeof UserProgressIndexRoute
  UserPurchaseHistoryIndexRoute: typeof UserPurchaseHistoryIndexRoute
  UserSettingsIndexRoute: typeof UserSettingsIndexRoute
  UserSupportIndexRoute: typeof UserSupportIndexRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserIndexRoute: UserIndexRoute,
  UserCoursesIdRouteRoute: UserCoursesIdRouteRouteWithChildren,
  UserCoursesIndexRoute: UserCoursesIndexRoute,
  UserNotificationsIndexRoute: UserNotificationsIndexRoute,
  UserProgressIndexRoute: UserProgressIndexRoute,
  UserPurchaseHistoryIndexRoute: UserPurchaseHistoryIndexRoute,
  UserSettingsIndexRoute: UserSettingsIndexRoute,
  UserSupportIndexRoute: UserSupportIndexRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRouteRoute: AboutRouteRouteWithChildren,
  AccreditationsRouteRoute: AccreditationsRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BlogRouteRoute: BlogRouteRouteWithChildren,
  CoursesRouteRoute: CoursesRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
  CertificateIdRoute: CertificateIdRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  TestIndexRoute: TestIndexRoute,
  VerifyIdIndexRoute: VerifyIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
